#!/usr/bin/env python

import sys

args = sys.argv

try:
  print ''.join([":scrabble_" + letter.lower() + ":"  if letter != " " else ":scrabble_blank:" for letter in " ".join(args[1:])])
except (AttributeError, TypeError) as e:
  sys.stderr.write("args must be strings")
except IndexError:
  sys.stderr.write("no args were present")
	

